# Generated by Django 6.1.1 on 2026-09-29 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dnevnik', '0005_profile_can_view_monitoring'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=20)),
                ('computer_name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computer_sessions', to='dnevnik.student')),
            ],
            options={
                'verbose_name': 'Prijava na računalo',
                'verbose_name_plural': 'Prijave na računala',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ime')),
                ('last_name', models.CharField(max_length=100, verbose_name='Prezime')),
                ('class_name', models.CharField(db_index=True, max_length=20, verbose_name='Razred')),
                ('computer_name', models.CharField(db_index=True, max_length=64, verbose_name='Računalo')),
                ('event_type', models.CharField(db_index=True, max_length=100, verbose_name='Vrsta')),
                ('details', models.TextField(blank=True, verbose_name='Detalji')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vrijeme (server)')),
                ('client_time', models.DateTimeField(blank=True, null=True, verbose_name='Vrijeme (računalo)')),
                ('search_name', models.CharField(db_index=True, editable=False, max_length=210)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='dnevnik.student')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='nadzor.computersession')),
            ],
            options={
                'verbose_name': 'Zapis aktivnosti',
                'verbose_name_plural': 'Zapisi aktivnosti',
                'ordering': ['-received_at', '-id'],
            },
        ),
    ]
