# Generated by Django 6.1.1 on 2026-09-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadzor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='identified',
            field=models.BooleanField(default=True, verbose_name='Identificiran'),
        ),
        migrations.AddField(
            model_name='computersession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
