# Generated by Django 6.1.1 on 2026-10-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadzor', '0002_session_end_and_identified'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(help_text='npr. roblox.com, tiktok, poki.com - poklapa se ako domena sadrži ovaj izraz.', max_length=255, unique=True, verbose_name='Domena ili izraz')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Kategorija')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nedopuštena stranica',
                'verbose_name_plural': 'Nedopuštene stranice',
                'ordering': ['pattern'],
            },
        ),
    ]
