# Generated by Django 6.1.1 on 2026-09-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnevnik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group_label',
            field=models.CharField(blank=True, choices=[('A', 'Grupa A'), ('B', 'Grupa B')], default='', help_text='Za satove koji se dijele u grupe (npr. praktikum).', max_length=1, verbose_name='Grupa'),
        ),
    ]
