# Generated by Django 6.1.1 on 2026-09-24 08:47

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnevnik', '0002_student_group_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-date', '-period', '-created_at'], 'verbose_name': 'Nastavni sat', 'verbose_name_plural': 'Nastavni satovi'},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lesson',
            name='period',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Sat u danu'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('school_class', 'subject', 'date', 'period', 'teacher')},
        ),
    ]
