# Generated by Django 6.1.1 on 2026-09-24 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnevnik', '0003_lesson_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory_teacher_name', models.CharField(blank=True, max_length=150, verbose_name='Učitelj teorije (ime i prezime)')),
                ('theory_teacher_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail učitelja teorije')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='dnevnik.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='dnevnik.subject')),
            ],
            options={
                'verbose_name': 'Predmet razreda',
                'verbose_name_plural': 'Predmeti razreda (učitelj teorije)',
                'ordering': ['subject__name'],
                'unique_together': {('school_class', 'subject')},
            },
        ),
    ]
