# Generated by Django 6.1.1 on 2026-09-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnevnik', '0004_classsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_view_monitoring',
            field=models.BooleanField(default=False, verbose_name='Smije vidjeti nadzor računala'),
        ),
    ]
