# Generated by Django 6.1.1 on 2026-09-30 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnevnik', '0005_profile_can_view_monitoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='period',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(14)], verbose_name='Sat u danu'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(db_collation='cro', max_length=100, verbose_name='Ime'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(db_collation='cro', max_length=100, verbose_name='Prezime'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(db_collation='cro', max_length=100, unique=True),
        ),
    ]
